id: A24CC2298
title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
  of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
type: translation
pechas:
- I42427493
- I34300FAD
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:32:24.841937
  last_modified_at: 2023-01-04 11:32:24.841948
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  I42427493/9A4F: B144
  I34300FAD/EE5B: B144
